/**
 * Behavior Analytics Types
 *
 * Type definitions for User Behavior Analytics (UBA) and Entity Behavior Analytics (EBA).
 */

/** User activity baseline definition */
export interface UserBaseline {
  userId: string
  createdAt: Date
  updatedAt: Date
  version: number
  loginPatterns: {
    timesOfDay: Map<number, number> // hour -> frequency
    daysOfWeek: Map<number, number> // day -> frequency
    averageLoginTime: number // minutes
    frequentLocations: Map<string, number> // location -> frequency
    frequentDevices: Map<string, number> // device -> frequency
  }
  accessPatterns: {
    frequentResources: Map<string, number> // resource -> frequency
    averageAccessFrequency: number // accesses per day
    peakAccessHours: number[]
    privilegeLevelDistribution: Map<string, number> // level -> frequency
  }
  dataAccessPatterns: {
    averageBytesPerDay: number
    frequentDataTypes: Map<string, number> // type -> frequency
    averageDataAccessDuration: number // milliseconds
    sensitiveDataAccessFrequency: number // per week
  }
  privilegePatterns: {
    elevationFrequency: number // per month
    roleSwitches: number // per month
    privilegeUsageDuration: number // average minutes
    frequentPrivileges: Map<string, number> // privilege -> frequency
  }
  riskFactors: {
    baselineRiskScore: number // 0-20
    failedLoginAttempts: number // typical per week
    accountAnomalies: string[]
  }
}

/** Entity baseline (device, service, etc.) */
export interface EntityBaseline {
  entityId: string
  entityType: 'device' | 'network' | 'application' | 'service' | 'api'
  createdAt: Date
  updatedAt: Date
  networkBehavior?: {
    typicalBandwidth: number // bytes per hour
    typicalConnections: number // per hour
    frequentPeers: Map<string, number> // peer -> frequency
    typicalPorts: Set<number>
  }
  applicationBehavior?: {
    typicalCPUUsage: number // percentage
    typicalMemoryUsage: number // percentage
    typicalErrorRate: number // percentage
    typicalResponseTime: number // milliseconds
  }
  apiUsage?: {
    typicalCallsPerHour: number
    typicalEndpoints: Map<string, number> // endpoint -> frequency
    typicalPayloadSize: number // bytes
    typicalLatency: number // milliseconds
  }
}

/** Activity event for analysis */
export interface ActivityEvent {
  userId?: string
  entityId?: string
  timestamp: Date
  type: 'login' | 'access' | 'data_access' | 'privilege_elevation' | 'api_call' | 'data_transfer' | 'failed_login'
  location?: string
  device?: string
  resource?: string
  dataSize?: number
  duration?: number
  privilegeLevel?: string
  sourceIP?: string
  riskFactors?: string[]
}

/** Behavioral anomaly detection result */
export interface BehavioralAnomaly {
  userId?: string
  entityId?: string
  anomalyId: string
  timestamp: Date
  anomalyType: 'temporal' | 'spatial' | 'volumetric' | 'pattern' | 'peer_group'
  anomalyScore: number // 0-100
  description: string
  evidencePoints: string[]
  expectedBehavior: string
  observedBehavior: string
  riskLevel: 'low' | 'medium' | 'high' | 'critical'
  suggestedActions: string[]
}

/** User risk profile */
export interface UserRiskProfile {
  userId: string
  overallRiskScore: number // 0-100
  riskLevel: 'low' | 'medium' | 'high' | 'critical'
  components: {
    temporalRisk: number
    spatialRisk: number
    volumetricRisk: number
    patternRisk: number
    peerGroupRisk: number
  }
  recentAnomalies: BehavioralAnomaly[]
  riskTrend: 'improving' | 'stable' | 'degrading'
  riskTrendScore: number
  lastUpdated: Date
  nextReviewDate: Date
}

/** Peer group definition */
export interface PeerGroup {
  groupId: string
  name: string
  groupingType: 'role' | 'department' | 'location' | 'custom'
  members: string[] // user IDs
  characteristics: {
    commonRole?: string
    commonDepartment?: string
    commonLocation?: string
    customCriteria?: string
  }
  baselineMetrics: {
    averageRiskScore: number
    medianRiskScore: number
    standardDeviation: number
  }
  createdAt: Date
  updatedAt: Date
}

/** Risk alert generated by the system */
export interface BehaviorAlert {
  alertId: string
  userId?: string
  entityId?: string
  timestamp: Date
  alertType: 'anomaly' | 'risk_threshold' | 'trend_change' | 'peer_outlier'
  severity: 'info' | 'warning' | 'critical'
  title: string
  description: string
  anomalies: BehavioralAnomaly[]
  investigation: {
    suggestedFocusAreas: string[]
    relatedEvents: string[]
    contextualInformation: Record<string, unknown>
  }
  recommendations: string[]
  status: 'open' | 'acknowledged' | 'resolved' | 'false_positive'
  assignedTo?: string
  createdAt: Date
  resolvedAt?: Date
}

/** Anomaly thresholds configuration */
export interface AnomalyThresholds {
  temporal: number // 0-100
  spatial: number
  volumetric: number
  pattern: number
  peerGroup: number
}
