/**
 * AI Copilot Studio Type Definitions
 * Complete type system for conversational workflow building
 */

import { Workflow, WorkflowNode, WorkflowEdge } from '../../types/workflowTypes';

/**
 * Intent types for workflow automation
 */
export type IntentType =
  | 'create'      // Build new workflow
  | 'modify'      // Edit existing workflow
  | 'delete'      // Remove workflow
  | 'debug'       // Fix errors
  | 'optimize'    // Improve performance
  | 'explain'     // Understand workflow
  | 'test'        // Test workflow
  | 'deploy'      // Deploy to production
  | 'schedule'    // Schedule execution
  | 'share';      // Share with team

/**
 * Intent classification result
 */
export interface IntentClassification {
  intent: IntentType;
  confidence: number;
  subIntent?: string;
  multiIntent: boolean;
  allIntents: Array<{
    intent: IntentType;
    confidence: number;
  }>;
  reasoning: string;
}

/**
 * Conversation turn in multi-turn dialogue
 */
export interface ConversationTurn {
  id: string;
  userMessage: string;
  copilotResponse: string;
  intent: IntentClassification;
  extractedParameters: ExtractedParameter[];
  suggestions: WorkflowSuggestion[];
  workflow?: Partial<Workflow>;
  timestamp: Date;
  confidence: number;
  requiresClarification: boolean;
  clarificationQuestions?: ClarificationQuestion[];
}

/**
 * Extracted parameter from natural language
 */
export interface ExtractedParameter {
  name: string;
  value: any;
  type: 'string' | 'number' | 'boolean' | 'object' | 'array' | 'node' | 'trigger' | 'condition';
  confidence: number;
  source: 'explicit' | 'inferred' | 'default';
  required?: boolean;
  position?: {
    start: number;
    end: number;
  };
  alternatives?: Array<{
    value: any;
    confidence: number;
  }>;
}

/**
 * Workflow suggestion generated by AI
 */
export interface WorkflowSuggestion {
  id: string;
  type: 'template' | 'optimization' | 'node' | 'connection' | 'alternative';
  title: string;
  description: string;
  confidence: number;
  priority: 'low' | 'medium' | 'high' | 'critical';
  applicability: number; // 0-100
  reasoning: string;
  data?: any;
  preview?: {
    before?: Partial<Workflow>;
    after: Partial<Workflow>;
    changes: string[];
  };
  estimatedImpact?: {
    performance?: number; // percentage improvement
    cost?: number;        // cost change
    reliability?: number; // reliability improvement
  };
}

/**
 * Clarification question when AI needs more info
 */
export interface ClarificationQuestion {
  id: string;
  question: string;
  type: 'choice' | 'text' | 'number' | 'boolean';
  options?: Array<{
    label: string;
    value: any;
    description?: string;
  }>;
  required: boolean;
  context: string;
  defaultValue?: any;
}

/**
 * Workflow template for quick start
 */
export interface WorkflowTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  complexity: 'simple' | 'moderate' | 'complex';
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
  requiredParameters: Array<{
    name: string;
    type: string;
    description: string;
    defaultValue?: any;
  }>;
  usageCount: number;
  rating: number;
  estimatedTime: number; // seconds
  estimatedCost: number; // dollars
}

/**
 * Copilot memory for personalization
 */
export interface CopilotMemory {
  userId: string;
  preferences: UserPreferences;
  history: ConversationHistory[];
  learnedPatterns: LearnedPattern[];
  favoriteTemplates: string[];
  customShortcuts: Record<string, any>;
  createdAt: Date;
  lastUpdated: Date;
}

/**
 * User preferences for copilot behavior
 */
export interface UserPreferences {
  language: string;
  verbosity: 'minimal' | 'normal' | 'detailed';
  autoSuggest: boolean;
  confirmActions: boolean;
  defaultTemplate?: string;
  preferredNodes: string[];
  avoidedNodes: string[];
  skillLevel: 'beginner' | 'intermediate' | 'advanced' | 'expert';
}

/**
 * Conversation history for context
 */
export interface ConversationHistory {
  sessionId: string;
  turns: ConversationTurn[];
  finalWorkflow?: Workflow;
  outcome: 'completed' | 'abandoned' | 'error';
  startedAt: Date;
  completedAt?: Date;
  satisfaction?: number; // 1-5 rating
}

/**
 * Learned pattern from user interactions
 */
export interface LearnedPattern {
  id: string;
  pattern: string;
  frequency: number;
  lastUsed: Date;
  context: Record<string, any>;
  confidence: number;
}

/**
 * Agent skill for no-code customization
 */
export interface AgentSkill {
  id: string;
  name: string;
  description: string;
  category: 'workflow' | 'data' | 'integration' | 'analysis' | 'automation';
  enabled: boolean;
  parameters: Array<{
    name: string;
    type: string;
    required: boolean;
    defaultValue?: any;
    description: string;
  }>;
  permissions: string[];
  costImpact: 'none' | 'low' | 'medium' | 'high';
}

/**
 * Custom agent configuration
 */
export interface AgentConfiguration {
  id: string;
  name: string;
  description: string;
  skills: string[]; // skill IDs
  parameters: Record<string, any>;
  permissions: string[];
  constraints: {
    maxExecutionTime?: number;
    maxCost?: number;
    allowedIntegrations?: string[];
  };
  createdAt: Date;
  lastModified: Date;
  deploymentStatus: 'draft' | 'testing' | 'deployed';
}

/**
 * Optimization recommendation from AI
 */
export interface OptimizationRecommendation {
  id: string;
  type: 'performance' | 'cost' | 'security' | 'reliability' | 'maintainability';
  title: string;
  description: string;
  currentState: string;
  proposedChange: string;
  impact: {
    performance?: number; // percentage improvement
    cost?: number;        // cost reduction in dollars
    reliability?: number; // reliability improvement (0-1)
  };
  effort: 'low' | 'medium' | 'high';
  priority: number; // 1-10
  autoApplicable: boolean;
  previewWorkflow?: Partial<Workflow>;
}

/**
 * Workflow generation request
 */
export interface WorkflowGenerationRequest {
  naturalLanguageDescription: string;
  context?: Record<string, any>;
  constraints?: {
    maxNodes?: number;
    maxCost?: number;
    preferredIntegrations?: string[];
    avoidedIntegrations?: string[];
  };
  template?: string; // template ID
  existingWorkflow?: Partial<Workflow>; // for modifications
}

/**
 * Workflow generation result
 */
export interface WorkflowGenerationResult {
  success: boolean;
  workflow?: Workflow;
  confidence: number;
  reasoning: string;
  alternatives?: Array<{
    workflow: Workflow;
    confidence: number;
    reasoning: string;
  }>;
  warnings?: string[];
  missingParameters?: string[];
  suggestions?: WorkflowSuggestion[];
}

/**
 * Intent classification training data
 */
export interface IntentTrainingExample {
  text: string;
  intent: IntentType;
  entities?: Array<{
    type: string;
    value: string;
    position: { start: number; end: number };
  }>;
}

/**
 * Copilot session state
 */
export interface CopilotSession {
  id: string;
  userId: string;
  currentTurn: number;
  turns: ConversationTurn[];
  workflowDraft?: Partial<Workflow>;
  context: Record<string, any>;
  startedAt: Date;
  lastActivityAt: Date;
  status: 'active' | 'paused' | 'completed' | 'abandoned';
}

/**
 * Template matching result
 */
export interface TemplateMatchResult {
  template: WorkflowTemplate;
  similarity: number;
  matchedKeywords: string[];
  missingParameters: string[];
  confidence: number;
  reasoning: string;
}

/**
 * Parameter extraction configuration
 */
export interface ParameterExtractionConfig {
  extractNumbers: boolean;
  extractDates: boolean;
  extractUrls: boolean;
  extractEmails: boolean;
  extractIntegrations: boolean;
  extractConditions: boolean;
  customPatterns?: Array<{
    name: string;
    pattern: RegExp;
    type: string;
  }>;
}

/**
 * Copilot analytics metrics
 */
export interface CopilotMetrics {
  totalSessions: number;
  completedWorkflows: number;
  averageCompletionTime: number; // seconds
  averageTurnsPerSession: number;
  intentAccuracy: number; // 0-1
  workflowGenerationSuccessRate: number; // 0-1
  userSatisfaction: number; // 1-5
  topIntents: Array<{
    intent: IntentType;
    count: number;
  }>;
  topTemplates: Array<{
    templateId: string;
    usageCount: number;
  }>;
  errorRate: number; // 0-1
}

/**
 * Streaming response chunk for real-time feedback
 */
export interface StreamingResponseChunk {
  type: 'text' | 'suggestion' | 'workflow' | 'question' | 'complete';
  data: any;
  timestamp: Date;
}

/**
 * Copilot configuration
 */
export interface CopilotConfig {
  maxTurnsPerSession: number;
  maxContextWindow: number; // number of previous turns to consider
  intentThreshold: number; // minimum confidence for intent classification
  enableStreaming: boolean;
  enableMemory: boolean;
  enableOptimizations: boolean;
  responseTimeoutMs: number;
  llmProvider: 'openai' | 'anthropic' | 'google' | 'azure';
  llmModel: string;
  temperature: number;
  maxTokens: number;
}
